import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import "asciinema-player/dist/bundle/asciinema-player.css";
import "../components/ui/cast-player.css";

const minecraftia = localFont({
  src: "./fonts/Minecraftia-Regular.ttf",
  variable: "--font-minecraftia",
  display: "swap",
  fallback: ["monospace"],
});

const mondwest = localFont({
  src: "./fonts/Mondwest-Regular.otf",
  variable: "--font-mondwest",
  display: "swap",
  fallback: ["monospace"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Change this to "mondwest" to switch the site's primary display font.
const ACTIVE_SITE_FONT: "minecraftia" | "mondwest" = "minecraftia";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-site-font={ACTIVE_SITE_FONT}
      className={`${minecraftia.variable} ${mondwest.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
